name: Python application

on:
  push:
    branches: [ main, fix_deploy ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install six Pillow numpy wxpython pyinstaller
    - name: Create bundle
      run: |
        cd %GITHUB_WORKSPACE%
        pyinstaller gui.py --noconsole
        rmdir"%GITHUB_WORKSPACE%\dist\gui\wx"
        xcopy "%RUNNER_TOOL_CACHE%\Python\3.10.0\x64\Lib\sit-packages\wx" "%GITHUB_WORKSPACE%\dist\gui" /E /H
        xcopy "%GITHUB_WORKSPACE%\Data" "%GITHUB_WORKSPACE%\dist\gui" /E /H
        rename "%GITHUB_WORKSPACE%\dist\gui\gui.exe" "%GITHUB_WORKSPACE%\dist\gui\English CAT"
      shell: cmd
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: CECAT
        path: ${{ github.workspace }}\dist\gui
        retention-days: 90
